export const companiesData = [
  {
    id: '728ed52f',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 567.8,
    foundedYear: 1990,
    knownTeam: [
      'Jonny Smitter',
      'Alice Nguyen',
      'Carlos Mendes',
      'Priya Kapoor',
      'Liam O’Connell',
      'Fatima Zahra',
      'Kenji Tanaka',
      'Chloe Dubois',
    ],
    favorited: false,
  },
  {
    id: 'b182ff3a',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 1234.5,
    foundedYear: 2005,
    knownTeam: ['Sarah Connor'],
    favorited: true,
  },
  {
    id: 'c3f64bb9',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office', 'Angel'],
    aum: 784.3,
    foundedYear: 2012,
    knownTeam: ['Eleanor Shellstrop'],
    favorited: true,
  },
  {
    id: 'f98b1db7',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 234.9,
    foundedYear: 2018,
    knownTeam: ['Chidi Anagonye'],
    favorited: false,
  },
  {
    id: 'e8d54b7c',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 910.1,
    foundedYear: 1998,
    knownTeam: ['Tahani Al-Jamil'],
    favorited: false,
  },
  {
    id: '1d76b9f2',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 1500.0,
    foundedYear: 2001,
    knownTeam: ['Jason Mendoza'],
    favorited: false,
  },
  {
    id: '72fb1a3e',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 345.6,
    foundedYear: 2015,
    knownTeam: ['Michael Scott'],
    favorited: false,
  },
  {
    id: '53d8a2c1',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 289.2,
    foundedYear: 1985,
    knownTeam: ['Pam Beesly'],
    favorited: false,
  },
  {
    id: 'd9f432eb',
    companyName: 'Lorem Ipsum inc',
    companyType: ['Family Office'],
    aum: 1050.7,
    foundedYear: 2010,
    knownTeam: ['Jim Halpert'],
    favorited: false,
  },
]
