// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ctcioauetpcvokqsezun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0Y2lvYXVldHBjdm9rcXNlenVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5ODA0MjQsImV4cCI6MjA1NzU1NjQyNH0.mMJOTQW5JCPYQMvpCyup519yMph606V_QT7e1Cri9BY";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  },
);
